dist: trusty
sudo: false
language: none
services:
  - docker
branches:
  only:
    - master
before_script:
  - pip install --user vim-vint
  - docker build -t vim-python-pep8-indent .
script:
  - docker run -ti --rm vim-python-pep8-indent
  - vint **/*.vim
