dist: trusty
sudo: false
language: none
services:
  - docker
branches:
  only:
    - master
cache:
  directories:
  - /tmp/dockerimgs
before_script:
  - pip install --user vim-vint
  - |
    DOCKER_IMG_FILE=/tmp/dockerimgs/vim-python-pep8-indent.2
    if [ -f "$DOCKER_IMG_FILE" ]; then
      docker load -i "$DOCKER_IMG_FILE"
    else
      docker build -t vim-python-pep8-indent .
      docker save vim-python-pep8-indent > "$DOCKER_IMG_FILE"
    fi
script:
  - docker run -ti -e VIMRUNNER_REUSE_SERVER=1 --rm vim-python-pep8-indent
  - vint **/*.vim
