dist: trusty
sudo: false
language: none
services:
  - docker
branches:
  only:
    - master
cache:
  directories:
  - /tmp/dockerimgs
before_script:
  - pip install --user vim-vint
  - |
    if [ -f /tmp/dockerimgs/vim-python-pep8-indent ]; then
      docker load -i /tmp/dockerimgs/vim-python-pep8-indent
    else
      docker build -t vim-python-pep8-indent .
      docker save vim-python-pep8-indent > /tmp/dockerimgs/vim-python-pep8-indent
    fi
script:
  - docker run -ti -e VIMRUNNER_REUSE_SERVER=1 --rm vim-python-pep8-indent
  - vint **/*.vim
